# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Shadows
tagline:          Multiplayer FPS game
description:      "A multiplayer FPS game to kill ghosts using machine guns"
url:              https://phoenixrrds.github.io/
baseurl:          /

author:
  name:           'PhoenixRRDS'
  url:            https://twitter.com/WBUTcoders

paginate:         5
excerpt_separator: "\n\n"

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/PhoenixRRDS

#Global vars
asset-img-path: /img/assets/
asset-path: /assets/
asset-download-path: /downloads/assets/

defaults:
  - scope:
      path: "_assets"
      type: assets
    values:
      layout: asset-view
      banner-img: Banner.jpg
      two-thirds-img: TwoThirds.jpg
      one-third-img: OneThird.jpg
      priority: 10
      show: true
      file-type: .zip

collections:
  assets:
    output: true
    permalink: /:collection/:title/
